name: Close answered discussions

permissions:
  discussions: write

on:
  # HACK
  push: {}
  # HACK

  # run daily
  schedule:
    - cron: "0 0 * * *"

  # allow manual trigger
  workflow_dispatch:

jobs:
  close-answered-discussions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        if: github.repository == 'renovatebot/renovate'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          show-progress: false

      - uses: actions/github-script@v8 # TODO
        if: github.repository == 'renovatebot/renovate'
        with:
          script: |
            const script = require('.github/workflows/close-answered-discussions/script.js')
            console.log(await script({github, context, discussionAnsweredDays: 30}))
